(function(){
  const platforms = [
    ['Yandex Music','https://cdn.simpleicons.org/yandex/ffffff','Яндекс Музыка'],['VK Music','https://cdn.jsdelivr.net/npm/simple-icons@v16/icons/vk.svg'],['Apple Music','https://cdn.jsdelivr.net/npm/simple-icons@v16/icons/applemusic.svg'],['Spotify','https://cdn.jsdelivr.net/npm/simple-icons@v16/icons/spotify.svg'],['YouTube Music','https://cdn.jsdelivr.net/npm/simple-icons@v16/icons/youtubemusic.svg'],['Deezer','https://cdn.jsdelivr.net/npm/simple-icons@v16/icons/deezer.svg'],['SoundCloud','https://cdn.jsdelivr.net/npm/simple-icons@v16/icons/soundcloud.svg'],['TikTok','https://cdn.jsdelivr.net/npm/simple-icons@v16/icons/tiktok.svg'],['Shazam','https://cdn.jsdelivr.net/npm/simple-icons@v16/icons/shazam.svg'],['TIDAL','https://cdn.jsdelivr.net/npm/simple-icons@v16/icons/tidal.svg'],['Amazon Music','https://cdn.jsdelivr.net/npm/simple-icons@v16/icons/amazonmusic.svg'],['MTS Music',null,'MTS'],['ZVUK','https://commons.wikimedia.org/wiki/Special:Redirect/file/Zvuk_(compact_logo).svg','ЗВУК'],['iHeartRadio','https://cdn.jsdelivr.net/npm/simple-icons@v16/icons/iheartradio.svg'],['Boomplay','https://commons.wikimedia.org/wiki/Special:Redirect/file/Boomplay_Logo.svg','BOOMPLAY']
  ];
  function injectStyles(){if(document.getElementById('platform-footer-style'))return;const style=document.createElement('style');style.id='platform-footer-style';style.textContent=`footer.site-footer{display:block!important;width:100%;padding-top:22px!important;color:var(--muted);font-size:10px;letter-spacing:.1em;text-transform:uppercase}.platform-footer{width:100%;max-width:760px;margin:0 auto 24px;display:grid;grid-template-columns:repeat(15,minmax(0,1fr));align-items:center;justify-items:center}.platform-logo{width:100%;height:20px;display:flex;align-items:center;justify-content:center;opacity:.92;transition:opacity .2s ease}.platform-logo img{display:block;width:auto;height:17px;max-width:42px;object-fit:contain;filter:brightness(0) invert(1)}.platform-wordmark{display:block;color:#f4f4f2;font-size:8px;line-height:1;font-weight:700;letter-spacing:-.025em;white-space:nowrap;text-transform:none}.footer-bottom{width:100%;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:8px;min-height:36px;text-align:center}@media(max-width:700px){footer.site-footer{padding-top:20px!important}.platform-footer{max-width:330px;margin-bottom:18px;grid-template-columns:repeat(5,minmax(0,1fr));row-gap:16px}.platform-logo{height:17px}.platform-logo img{height:14px;max-width:34px}.platform-wordmark{font-size:7px}}`;document.head.appendChild(style)}
  function addPlatformFooter(){const footer=document.querySelector('footer.site-footer, footer');if(!footer||footer.querySelector('.platform-footer'))return;injectStyles();const block=document.createElement('div');block.className='platform-footer';platforms.forEach(([name,src,fallback])=>{const item=document.createElement('span');item.className='platform-logo';item.title=name;if(!src){const w=document.createElement('span');w.className='platform-wordmark';w.textContent=fallback||name;item.appendChild(w)}else{const img=document.createElement('img');img.src=src;img.alt=name;img.loading='eager';img.addEventListener('error',()=>{if(item.querySelector('.platform-wordmark'))return;img.remove();const w=document.createElement('span');w.className='platform-wordmark';w.textContent=fallback||name;item.appendChild(w)},{once:true});item.appendChild(img)}block.appendChild(item)});const children=[...footer.children].filter(el=>el!==block);let bottom=footer.querySelector('.footer-bottom');if(!bottom){bottom=document.createElement('div');bottom.className='footer-bottom';children.forEach(el=>{const t=el.textContent.trim();if(t==='PRYCOT. — 2026')el.classList.add('footer-year');if(t==='INDEPENDENT MUSIC LABEL')el.classList.add('footer-label');bottom.appendChild(el)})}footer.innerHTML='';footer.appendChild(block);footer.appendChild(bottom)}
  function addDashboardGuideToMenu(){const menus=document.querySelectorAll('.menu-left');menus.forEach(menu=>{if(menu.querySelector('a[href="dashboard-guide.html"]'))return;const account=menu.querySelector('a[href="account.html"]');if(!account)return;const link=document.createElement('a');link.href='dashboard-guide.html';link.textContent='Dashboard Guide';link.setAttribute('data-dashboard-guide','true');account.insertAdjacentElement('afterend',link);const current=(location.pathname.split('/').pop()||'index.html').toLowerCase();if(current==='dashboard-guide.html')link.classList.add('active-page')})}
  function init(){addDashboardGuideToMenu();addPlatformFooter();setTimeout(addDashboardGuideToMenu,250);setTimeout(addDashboardGuideToMenu,1000)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
  window.addEventListener('load',addDashboardGuideToMenu);
})();